# Generated by Django 4.2.4 on 2024-12-13 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConversionRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crypto_symbol", models.CharField(max_length=10)),
                ("fiat_currency", models.CharField(default="USD", max_length=10)),
                ("rate", models.FloatField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="KeypairModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Merchant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("unique_sk", models.CharField(max_length=300, unique=True)),
                ("public_key", models.CharField(max_length=128)),
                ("private_key", models.TextField()),
                ("fiat_currency", models.CharField(default="NAIRA", max_length=10)),
                ("fiat_account_number", models.CharField(max_length=10)),
                ("fiat_bank_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount_crypto", models.DecimalField(decimal_places=8, max_digits=18)),
                ("amount_fiat", models.DecimalField(decimal_places=2, max_digits=12)),
                ("status", models.CharField(default="PENDING", max_length=20)),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("keypair_derivative", models.TextField()),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.merchant"
                    ),
                ),
            ],
        ),
    ]
