# Generated by Django 4.2.4 on 2024-12-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="description",
            field=models.CharField(default="No description", max_length=200),
        ),
    ]
